### ISSUE TITLE
Bug on Resize -> mis-calculated margin-bottom

### ISSUE THREAD

**Issue by joschka** [soenkekluth/react-sticky-state#5] opened 2016-07-07 08:19 UTC
Hi Sönke,

there seems to be a bug regarding the calculation of the _margin-bottom_ of _is-absolute_ elements on resize. The margin-bottom get's quite big, eg. 171097px and causes the page to become really long (whitespace at the end of the page)

How to reproduce:
1. go to demo page using Chrome: https://rawgit.com/soenkekluth/react-sticky-state/master/examples/index.html
2. scroll down until the first red "Fixed to viewport top A." element (#top-a) becomes "is-absolute".
3. Inspect that "is-absolute" element and watch the margin-bottom inline style
4. Resize the window
5. Observe that the margin-bottom value increases with every resize event
- Scrolling up again fixes the calculated value (the calculation onScroll seems to be ok)
- the value is increased by a fixed value on every resize event

Would be great, if you can have a look. When I find time, I will do also.

<img width="747" alt="" src="https://cloud.githubusercontent.com/assets/393443/16646529/e2c4bb28-442a-11e6-97bd-3e196ca89eb7.png">

**Comment by soenkekluth** [comment] 2016-07-08 02:46
ok i will look into it. thx

**Comment by henrikra** [comment] 2016-09-13 17:58
I can confirm this bug! Please fix this very soon because I think we have to change sticky library in our project until this isn't fixed :/

**Comment by henrikra** [comment] 2016-09-14 06:20
Looks like only React version of sticky-state library has this "resize bug". I did workaround by using non-React version of sticky-state. My component looks like this and not it works great :)

```
import React from "react";
import StickyState from "sticky-state";

const StickyExampleComponent = React.createClass({
  componentDidMount() {
    new StickyState(document.querySelectorAll(".element-i-want-to-be-sticky"));
  },

  render() {
    return (
      <div className="element-i-want-to-be-sticky">
        Look I am sticky!
      </div>
    );
  }
});

export default StickyExampleComponent;
```

**Comment by soenkekluth** [comment] 2016-09-16 03:08
@henrikra @joschka yes you are right. margin-top and bottom support is already implemented in the newsest version of sticky-state https://github.com/soenkekluth/sticky-state
example: https://rawgit.com/soenkekluth/sticky-state/master/examples/index.html

I will soon port it to the react version!

**Comment by soenkekluth** [comment] 2016-09-16 06:29
should be fixed in v2.0.0 https://rawgit.com/soenkekluth/react-sticky-state/master/examples/index.html

**Comment by soenkekluth** [comment] 2016-09-23 02:11
@joschka @henrikra does it work now? close?

**Comment by henrikra** [comment] 2016-09-23 06:32
For me resizing works now on react version on sticky-state :)

**Comment by soenkekluth** [comment] 2016-09-23 09:29
@henrikra its hard to keep both libs up to date. I will make the core calculations an own module.

**Comment by henrikra** [comment] 2016-09-23 21:20
Very good idea!

**Comment by soenkekluth** [comment] 2016-12-03 10:49
everything should be fine with the new versions. (2.1.4)

**Closed as completed by soenkekluth** 2016-12-03 10:49 UTC
